"""Representation of a candidate heuristic_score program.

A ``Program`` is a weighted sum of *features* computed from the graph and
its invariants. Each feature is a deterministic, cheap-to-evaluate function
of ``G`` and the invariants dict. The program is fully reconstructible from
its ``terms`` list, so we can serialise / deserialise / mutate / cross-over
without ever touching Python source code at runtime.

When exporting to disk (for inclusion in the GitHub repo) we also generate
real Python source that matches the *form imposee* in the project statement.
"""

from dataclasses import dataclass, field
from typing import List, Tuple
import math
import random


# ---------------------------------------------------------------------------
# Feature library
# ---------------------------------------------------------------------------
# Each feature is a function (G, invariants) -> float. They MUST handle missing
# invariants gracefully (the evolved score is also called on tiny graphs).
#
# We keep the menu deliberately small — wide enough to express the structural
# intuitions that humans would write, narrow enough that random combinations
# remain interpretable.

def _safe(inv, k, default=0.0):
    v = inv.get(k, default)
    try:
        return float(v)
    except Exception:
        return default


def feat_violation(G, inv):
    # The principal term: violation itself. Always present and always
    # weighted positively (we maximise it).
    return _safe(inv, "_violation")


def feat_n(G, inv):
    return float(G.number_of_nodes())


def feat_m(G, inv):
    return float(G.number_of_edges())


def feat_density(G, inv):
    n = G.number_of_nodes()
    if n < 2:
        return 0.0
    return 2.0 * G.number_of_edges() / (n * (n - 1))


def feat_density_balance(G, inv):
    # Negative-only term: how far from a balanced density we are.
    return -abs(feat_density(G, inv) - 0.5)


def feat_leaves(G, inv):
    return float(sum(1 for _, d in G.degree() if d == 1))


def feat_isolated_penalty(G, inv):
    return -float(sum(1 for _, d in G.degree() if d == 0))


def feat_max_deg(G, inv):
    return float(max((d for _, d in G.degree()), default=0))


def feat_min_deg(G, inv):
    return float(min((d for _, d in G.degree()), default=0))


def feat_avg_deg(G, inv):
    n = G.number_of_nodes()
    if n == 0:
        return 0.0
    return 2.0 * G.number_of_edges() / n


def feat_log_n(G, inv):
    return math.log1p(G.number_of_nodes())


def feat_sqrt_n(G, inv):
    return math.sqrt(G.number_of_nodes())


def feat_n_squared(G, inv):
    n = G.number_of_nodes()
    return float(n * n)


def feat_inv_x(G, inv):
    return _safe(inv, "_x_value")


def feat_inv_y(G, inv):
    return _safe(inv, "_y_value")


def feat_inv_xy_gap(G, inv):
    return _safe(inv, "_y_value") - _safe(inv, "_x_value")


def feat_triangles_proxy(G, inv):
    # Local triangle density without computing the invariant
    n = G.number_of_nodes()
    if n < 3:
        return 0.0
    return feat_density(G, inv) * G.number_of_edges()


def feat_size_penalty(G, inv):
    return -float(G.number_of_nodes())


FEATURES = {
    "violation": feat_violation,
    "n": feat_n,
    "m": feat_m,
    "density": feat_density,
    "density_balance": feat_density_balance,
    "leaves": feat_leaves,
    "isolated_penalty": feat_isolated_penalty,
    "Delta": feat_max_deg,
    "delta": feat_min_deg,
    "avg_deg": feat_avg_deg,
    "log_n": feat_log_n,
    "sqrt_n": feat_sqrt_n,
    "n_squared": feat_n_squared,
    "x_value": feat_inv_x,
    "y_value": feat_inv_y,
    "xy_gap": feat_inv_xy_gap,
    "triangles_proxy": feat_triangles_proxy,
    "size_penalty": feat_size_penalty,
}

ALL_FEATURE_NAMES = list(FEATURES.keys())


# Features whose weight is allowed to be selected/perturbed but which are not
# allowed to vanish: violation is the principal term.
PROTECTED_FEATURES = {"violation"}


# ---------------------------------------------------------------------------
# Program
# ---------------------------------------------------------------------------

# A program is exposed as a Python source string matching the form imposed by
# the project statement, plus a structured `terms` list that lets us mutate /
# serialise it programmatically.

PYTHON_HEADER = '''"""Auto-generated by funsearch.runner — DO NOT EDIT BY HAND.

This file matches the form imposee by the project statement: it exports a
function ``heuristic_score(G, invariants, conjecture)`` returning a numeric
score to be maximised by the local search.
"""

import math


def heuristic_score(G, invariants, conjecture):
    """G : graphe NetworkX
       invariants : dictionnaire des invariants calcules
       conjecture : objet decrivant la conjecture
       retourne un score numerique a maximiser
    """
    x_name = conjecture.x_invariant
    y_name = conjecture.y_invariant
    x = invariants.get(x_name, 0)
    y = invariants.get(y_name, 0)
    violation = conjecture.violation(x, y)
    if violation > 1e-9:
        return 1e6 + violation

    n = invariants.get("n", G.number_of_nodes())
    m = invariants.get("m", G.number_of_edges())
    if n <= 1:
        return violation - 100.0

    delta = min((d for _, d in G.degree()), default=0)
    Delta = max((d for _, d in G.degree()), default=0)
    diam = invariants.get("diam", 0)
    gamma = invariants.get("gamma", 0)
    alpha = invariants.get("alpha", 0)
    tau = invariants.get("tau", 0)
    triangles = invariants.get("triangles", 0)

    avg_deg = (2.0 * m / n) if n > 0 else 0.0
    density = (2.0 * m / (n * (n - 1))) if n > 1 else 0.0
    leaves = sum(1 for _, d in G.degree() if d == 1)
    isolated = sum(1 for _, d in G.degree() if d == 0)
    density_balance = -abs(density - 0.5)
    log_n = math.log1p(n)
    sqrt_n = math.sqrt(n)
    n_squared = n * n
    x_value = float(x) if isinstance(x, (int, float)) else 0.0
    y_value = float(y) if isinstance(y, (int, float)) else 0.0
    xy_gap = y_value - x_value
    triangles_proxy = density * m
    size_penalty = -float(n)

    return (
{terms_block}
    )
'''


@dataclass
class Program:
    terms: List[Tuple[float, str]] = field(default_factory=list)

    # -------------------------------------------------------------------
    # Scoring
    # -------------------------------------------------------------------
    def score(self, G, invariants, conjecture):
        # Inline implementation. Note that `violation` is read from inv via the
        # special key "_violation" inserted by the caller.
        x = invariants.get(conjecture.x_invariant, 0)
        y = invariants.get(conjecture.y_invariant, 0)
        v = conjecture.violation(x, y)
        if v > 1e-9:
            return 1e6 + v
        if G.number_of_nodes() <= 1:
            return v - 100.0
        local_inv = dict(invariants)
        local_inv["_violation"] = v
        local_inv["_x_value"] = float(x) if isinstance(x, (int, float)) else 0.0
        local_inv["_y_value"] = float(y) if isinstance(y, (int, float)) else 0.0
        total = 0.0
        for w, name in self.terms:
            fn = FEATURES.get(name)
            if fn is None:
                continue
            try:
                total += w * fn(G, local_inv)
            except Exception:
                continue
        return total

    # -------------------------------------------------------------------
    # Serialisation
    # -------------------------------------------------------------------
    def to_python(self):
        if not self.terms:
            body = "        0.0"
        else:
            lines = []
            for w, name in self.terms:
                sign = "+" if w >= 0 else "-"
                lines.append(f"        {sign} {abs(w):.4f} * {name}")
            # First line should not start with +
            if lines[0].lstrip().startswith("+"):
                lines[0] = lines[0].replace("+", " ", 1)
            body = "\n".join(lines)
        return PYTHON_HEADER.format(terms_block=body)

    def to_dict(self):
        return {"terms": [(w, n) for w, n in self.terms]}

    @classmethod
    def from_dict(cls, data):
        return cls(terms=[(float(w), n) for w, n in data["terms"]])

    def signature(self):
        # Used for de-duplication. Order-insensitive, weights rounded.
        items = sorted((name, round(w, 3)) for w, name in self.terms)
        return tuple(items)

    # -------------------------------------------------------------------
    # Mutation
    # -------------------------------------------------------------------
    def copy(self):
        return Program(terms=list(self.terms))

    def mutate(self, rng=None):
        rng = rng or random
        new = self.copy()
        ops = ["perturb_weight", "add_term", "remove_term", "swap_feature",
               "flip_sign", "rescale"]
        op = rng.choice(ops)

        if op == "perturb_weight" and new.terms:
            idx = rng.randrange(len(new.terms))
            w, name = new.terms[idx]
            factor = rng.uniform(0.5, 1.8)
            shift = rng.uniform(-0.3, 0.3)
            new.terms[idx] = (w * factor + shift, name)
        elif op == "add_term":
            name = rng.choice(ALL_FEATURE_NAMES)
            w = rng.uniform(-1.5, 1.5)
            new.terms.append((w, name))
        elif op == "remove_term" and len(new.terms) > 2:
            # Don't remove the protected ones
            candidates = [i for i, (_, name) in enumerate(new.terms)
                          if name not in PROTECTED_FEATURES]
            if candidates:
                new.terms.pop(rng.choice(candidates))
        elif op == "swap_feature" and new.terms:
            idx = rng.randrange(len(new.terms))
            w, _ = new.terms[idx]
            new.terms[idx] = (w, rng.choice(ALL_FEATURE_NAMES))
        elif op == "flip_sign" and new.terms:
            idx = rng.randrange(len(new.terms))
            w, name = new.terms[idx]
            if name not in PROTECTED_FEATURES:
                new.terms[idx] = (-w, name)
        elif op == "rescale":
            factor = rng.uniform(0.7, 1.4)
            new.terms = [(w * factor, n) for w, n in new.terms]

        new = new.cleaned()
        return new

    @staticmethod
    def crossover(p1, p2, rng=None):
        rng = rng or random
        # Pick a subset from each parent
        k1 = rng.randint(1, max(1, len(p1.terms)))
        k2 = rng.randint(1, max(1, len(p2.terms)))
        terms = list(rng.sample(p1.terms, min(k1, len(p1.terms)))) + \
                list(rng.sample(p2.terms, min(k2, len(p2.terms))))
        child = Program(terms=terms).cleaned()
        return child

    def cleaned(self):
        # Merge duplicates by feature name and drop near-zero weights.
        merged = {}
        for w, name in self.terms:
            merged[name] = merged.get(name, 0.0) + w
        # Always make sure violation is present with a positive weight
        if merged.get("violation", 0.0) < 0.1:
            merged["violation"] = 1.0
        # Bound weights to avoid explosion
        out = []
        for name, w in merged.items():
            if abs(w) < 1e-4 and name not in PROTECTED_FEATURES:
                continue
            w = max(-100.0, min(100.0, w))
            out.append((round(w, 4), name))
        out.sort()
        return Program(terms=out)


# ---------------------------------------------------------------------------
# Hand-crafted seeds for the database. These match the level of detail of the
# example in the project statement and the current static heuristic.
# ---------------------------------------------------------------------------

def seed_programs():
    seeds = []

    # 1) Pure violation (baseline from project statement)
    seeds.append(Program(terms=[(1.0, "violation")]))

    # 2) Example given in the project statement
    seeds.append(Program(terms=[
        (10.0, "violation"),
        (0.3, "n"),  # diam not exposed directly; use n proxy
        (0.2, "Delta"),
        (0.1, "triangles_proxy"),
        (-0.05, "n"),
        (-0.2, "density_balance"),
    ]).cleaned())

    # 3) Current static heuristic (rough port of src/scoring.py)
    seeds.append(Program(terms=[
        (1.0, "violation"),
        (0.001, "n"),
        (0.05, "leaves"),
        (0.005, "m"),
        (1.0, "density_balance"),
        (-0.5, "isolated_penalty"),
    ]).cleaned())

    # 4) Aggressive structural seed
    seeds.append(Program(terms=[
        (1.0, "violation"),
        (0.02, "n"),
        (0.1, "leaves"),
        (0.05, "Delta"),
        (-0.01, "isolated_penalty"),
        (0.3, "xy_gap"),
    ]).cleaned())

    # 5) Compact seed (penalises large graphs)
    seeds.append(Program(terms=[
        (1.0, "violation"),
        (-0.05, "n"),
        (0.2, "xy_gap"),
        (0.5, "density_balance"),
    ]).cleaned())

    return seeds
